import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/global/styles/global.scss";
import { LayoutFooter } from "@/components/layout/LayoutFooter";
import { LayoutNav } from "@/components/layout/LayoutNav";
import { ToastContainer } from "react-toastify";
import { HeaderTagContextProvider } from "@/contexts/HeaderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col`}
      >
        <HeaderTagContextProvider>
          <div id="modal-root-element" />
          <ToastContainer position="top-center" />
          <LayoutNav />
          <div className="grow">{children}</div>
          <LayoutFooter />
        </HeaderTagContextProvider>
      </body>
    </html>
  );
}
